{{- if .Values.deployment.enabled -}}
{{- $fullName := include "uclalib-helm-generic.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uclalib-helm-generic.fullname" . }}
  labels:
    {{- include "uclalib-helm-generic.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ (.Values.deployment.strategy).type | default "RollingUpdate" | quote }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "uclalib-helm-generic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.configmap.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.externalsecrets.enabled }}
        {{- if .Values.externalsecrets.secrets.application -}}
        checksum/externalsecret: {{ include (print $.Template.BasePath "/application-externalsecrets.yaml") . | sha256sum }}
        {{- end }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "uclalib-helm-generic.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.pv.nfs.enabled }}
      volumes:
      {{- range $k, $v := .Values.pv.nfs.mounts }}
      - name: {{ $fullName }}-{{ $k }}
        persistentVolumeClaim:
          claimName: {{ $fullName }}-{{ $k }}
          readOnly: {{ $v.readOnly }}
      {{- end}}
      {{- range $k, $v := .Values.pv.default.mounts }}
      - name: {{ $fullName }}-{{ $k }}
        persistentVolumeClaim:
          claimName: {{ $fullName }}-{{ $k }}
      {{- end}}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uclalib-helm-generic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "uclalib-helm-generic.fullname" . }}
          {{- if .Values.pv.enabled }}
          volumeMounts:
          {{- range $k, $v := .Values.pv.nfs.mounts }}
          - name: {{ $fullName }}-{{ $k }}
            mountPath: {{ $v.mountPath }}
          {{- end }}
          {{- range $k, $v := .Values.pv.default.mounts }}
          - name: {{ $fullName }}-{{ $k }}
            mountPath: {{ $v.mountPath }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.configmap.enabled .Values.externalsecrets.enabled }}
          envFrom:
            {{- if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ include "uclalib-helm-generic.fullname" . }}
            {{- end }}
            {{- if .Values.externalsecrets.enabled }}
            {{- if .Values.externalsecrets.secrets.application -}}
            - secretRef:
                name: {{ include "uclalib-helm-generic.fullname" . }}
            {{- end }}
            {{- end }}
          {{- end }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe  | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
