{{- if .Values.externalsecrets.enabled -}}
{{- if .Values.externalsecrets.secrets.dockerhub -}}
{{- $fullName := include "uclalib-helm-generic.fullname" . -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-dockerhub-externalsecret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ $.Values.externalsecrets.ref }}
    kind: ClusterSecretStore
  target:
    name: {{ $fullName }}-dockerhub-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .creds }}` }}"
  data:
    {{- toYaml .Values.externalsecrets.secrets.dockerhub.data | nindent 4 }}
{{- end }}
{{- end }}
