{{- if .Values.pv.nfs.enabled -}}
{{- $fullName := include "uclalib-helm-generic.fullname" . -}}
{{ range $k, $v := .Values.pv.nfs.mounts }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ $k }}
  {{- with $v.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ $v.mode }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ $v.capacity }}
  volumeName: {{ $fullName }}-{{ $k }}
{{- end }}
{{- end }}
